///////////////////////////////////////////////////////////
// @author : Mandeep Bisht
///////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////
// Function that will catch async error
module.exports = fn => {
    return (req, res, next) => {
        fn(req, res, next)
            .catch(next);
    }
}
///////////////////////////////////////////////////////////